apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jenkins.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jenkins.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}
        ports:
        - name: http-port
          containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: {{ .Values.volume.name }}
          mountPath: /var/jenkins_vol
      volumes:
      - name: {{ .Values.volume.name }}
        emptyDir: {}