replicaCount: 1

image:
  repository: jenkins/jenkins:2.235.1-lts-alpine

service:
  name: jenkins
  port: 8080
  targetPort: 8080
  nodePort: 30000

container:
  name: jenkins
  
volume:
  name: jenkins-vol